s3_info:
  a-and-c:
    bucket_name: xxxx
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
    file_name: 'pms-reservations/'
    delete_after_upload: true

  sunshine:
    bucket_name: xxxx
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
    file_name: 'pms-reservations/'
    delete_after_upload: true

  kanon:
    bucket_name: xxxx
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
    file_name: 'pms-reservations/'
    delete_after_upload: true

  kureha:
    bucket_name: xxxx
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
    file_name: 'pms-reservations/'
    delete_after_upload: true

  goshobo:
    bucket_name: xxxx
    access_key_id: 'xxxx'
    secret_access_key: 'xxxx'
    file_name: 'pms-reservations/'
    delete_after_upload: true

csv:
  input_directory: csv
  output_directory: processed-csv
